
services:
  backend:
    build: ./backend
    container_name: paytm-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - paytm-net

  frontend:
    build: ./frontend
    container_name: paytm-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - paytm-net

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/paytm.crt:/etc/ssl/paytm.crt:ro
      - /etc/ssl/paytm.key:/etc/ssl/paytm.key:ro
    depends_on:
      - backend
      - frontend
    networks:
      - paytm-net
networks:
  paytm-net:
    driver: bridge
